name: CI Pipeline

on:
  push:
    paths-ignore:
      - 'images/**'
      # - 'README.md'

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Test-Results
        path: "**/test-results.trx"

  publish-test-results:
    name: "Publish Tests Results"
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write # SonarCloud would be sufficient to read, but test reporter also wrotes to PR
      
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: test-results
        with:
          files: "artifacts/**/test-results.trx"
  
      - name: Set badge color
        shell: bash
        run: |
          case ${{ fromJSON( steps.test-results.outputs.json ).conclusion }} in
            success)
              echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
              ;;
            failure)
              echo "BADGE_COLOR=800000" >> $GITHUB_ENV
              ;;
            neutral)
              echo "BADGE_COLOR=696969" >> $GITHUB_ENV
              ;;
          esac
  
      - name: Create badge
        uses: emibcn/badge-action@v2.0.2
        with:
          label: Tests
          status: '${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.tests }} tests, ${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs }} runs: ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}'
          color: ${{ env.BADGE_COLOR }}
          path: badge.svg
  
      - name: Upload badge to Gist
        # Upload only for main branch
  #      if: >
  #        github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'main' ||
  #        github.event_name != 'workflow_run' && github.ref == 'refs/heads/main'
        uses: andymckay/append-gist-action@0.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistURL: https://gist.githubusercontent.com/${{ vars.GIST_USER }}/${{ vars.GIST_ID }}
          file: badge.svg