name: CI Pipeline

on:
  push:
    paths-ignore:
      - 'images/**'
      # - 'README.md'

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results
  checks: write # for test-reporter

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: dotnet tests          # Name of the check run which will be created
        path: "**/test-results.trx"      # Path to test results
        reporter: dotnet-trx        # Format of test results
        fail-on-error: true

  analyse:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: |
            -Dsonar.projectKey=mcce22extreme_ss2023-ineni-smart-office
            -Dsonar.organization=mcce22extreme